ALTER TYPE "TipoOcorrencia" RENAME VALUE 'INADIMPLENCIA_LOCATICIA' TO 'DEBITO_LOCATICIO_ABERTO';
ALTER TYPE "TipoOcorrencia" RENAME VALUE 'MULTA_CONTRATUAL' TO 'MULTA_RESCISORIA_NAO_QUITADA';
ALTER TYPE "TipoOcorrencia" RENAME VALUE 'DEPREDACAO_DANOS_IMOVEL' TO 'DANOS_IMOVEL';

ALTER TYPE "TipoOcorrencia" ADD VALUE 'ENTREGA_IRREGULAR_IMOVEL';
ALTER TYPE "TipoOcorrencia" ADD VALUE 'UTILIZACAO_INDEVIDA_IMOVEL';
ALTER TYPE "TipoOcorrencia" ADD VALUE 'ACAO_JUDICIAL_LOCACAO';

CREATE TYPE "SituacaoOcorrencia" AS ENUM ('EM_ABERTO', 'EM_COBRANCA', 'EM_NEGOCIACAO', 'EM_PROCESSO_JUDICIAL');

CREATE TYPE "FaixaValorOcorrencia" AS ENUM ('ATE_5_MIL', 'DE_5_MIL_A_20_MIL', 'ACIMA_20_MIL');

ALTER TABLE "ocorrencias" RENAME COLUMN "descricao" TO "observacoes";

ALTER TABLE "ocorrencias" ADD COLUMN "dataNascimentoInquilino" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "ocorrencias" ADD COLUMN "dataOcorrencia" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "ocorrencias" ADD COLUMN "situacaoAtual" "SituacaoOcorrencia" NOT NULL DEFAULT 'EM_ABERTO';
ALTER TABLE "ocorrencias" ADD COLUMN "faixaValor" "FaixaValorOcorrencia" NOT NULL DEFAULT 'ATE_5_MIL';

ALTER TABLE "ocorrencias" ALTER COLUMN "dataNascimentoInquilino" DROP DEFAULT;
ALTER TABLE "ocorrencias" ALTER COLUMN "dataOcorrencia" DROP DEFAULT;
ALTER TABLE "ocorrencias" ALTER COLUMN "situacaoAtual" DROP DEFAULT;
ALTER TABLE "ocorrencias" ALTER COLUMN "faixaValor" DROP DEFAULT;
